### ISSUE TITLE
Friend Chat

### ISSUE THREAD

**Issue by seisvelas** [BrunoTorresF/next-sandbox#2]
Hey! I just made this to chat with you since I don't know the best way. Sup!

**Comment by BrunoTorresF** [comment]
Hey dude. What's up? What's with "Alex Vazquez"?

**Comment by seisvelas** [comment]
Vazquez is my maternal last name! Just saying hi. Hope you're well! What's your favorite state?

**Comment by seisvelas** [comment]
:(
